public enum QingFun {
	ENQUEUE_AT_FRONT_DF, ENQUEUE_AT_FRONT_ID, ENQUEUE_AT_END, ORDERED_INSERT, A_HEURISTIC_ONE, A_HEURISTIC_TWO, A_HEURISTIC_THREE, A_HEURISTIC_FOUR,  Q_HEURISTIC_ONE, Q_HEURISTIC_TWO, Q_HEURISTIC_THREE, Q_HEURISTIC_FOUR;
}